# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  mode: keep-existing
  draft: false
  name_template: "{{ .Tag }}"
  footer: |
    **Full Changelog**: https://github.com/bartventer/go-template-playground/compare/{{ .PreviousTag }}...{{ if .IsNightly }}nightly{{ else }}{{ .Tag }}{{ end }}

    {{ if not .IsNightly }}
    ## Contributing

    This release is made possible by the contributions of our amazing community!

    Want to help improve this project?
    You can [contribute with code](https://github.com/bartventer/go-template-playground/CONTRIBUTING.md).

    ---
    <div display="flex" align-items="center" flex-direction="column" width="100%" style="display:flex !important; align-items:center !important; flex-direction:column !important; width:100%;">
    <p align="center" style="text-align:center;">
    <img src="https://i.imgur.com/SvFgb1L.png" alt="Go Template Playground Logo" width="auto" height="200" style="width:auto; height:200px;"/>
    </p>
    <p align="center" style="text-align:center;"><sub><small>Photo by <a href="https://github.com/ashleymcnamara">Ashley McNamara</a>, via <a href="https://github.com/ashleymcnamara/gophers">ashleymcnamara/gophers</a> (CC BY-NC-SA 4.0)</small></sub></p>
    </div>
    {{ end }}
