name: "Deploy to GitHub Pages"
description: "Action which sets up, uploads the build artifact and deploys to GitHub Pages"
branding:
  icon: "upload-cloud"
  color: "green"
inputs:
  artifact-path:
    description: "Path of the directory containing the static assets."
    required: false
    default: "./www/dist"
  preview:
    description: "Deploy to a preview environment"
    required: false
    default: "false"
outputs:
  page_url:
    description: "URL to deployed GitHub Pages"
    value: ${{ steps.deployment.outputs.page_url }}
runs:
  using: "composite"
  steps:
    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.artifact-path }}

    - name: Deploy to GitHub Pages
      if: ${{ !inputs.preview }}
      uses: actions/deploy-pages@v4
      with:
        preview: ${{ inputs.preview }}
