// Code generated by "stringer -type=Action -trimprefix=Action"; DO NOT EDIT.

package playground

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionProcessTemplate-0]
	_ = x[ActionTransformData-1]
}

const _Action_name = "ProcessTemplateTransformData"

var _Action_index = [...]uint8{0, 15, 28}

func (i Action) String() string {
	if i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
