name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go-version: [1.24.x]
        include:
          - go-version: 1.24.x
            upload-coverage: true

    runs-on: ${{ matrix.os }}
    env:
      COVERAGE_DIR: coverage
      COVERPROFILE: coverage.out
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: ${{ github.workspace }}/go.sum

      - name: Build
        shell: bash
        run: make build/wasm

      - name: Test
        shell: bash
        run: make test/wasm

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.upload-coverage }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.COVERAGE_DIR }}/${{ env.COVERPROFILE }}
          disable_search: true
