name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    branches: [master]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: "Build"
        run: make build

      - name: Prepare tag
        id: prepare_tag
        shell: bash
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -e
          TAG_NAME=$(echo "${{ github.ref }}" | sed -e 's/refs\/tags\///')
          echo "DEPLOY_TAG_NAME=deploy-${TAG_NAME}" >> "${GITHUB_OUTPUT}"

      - name: "Deploy to GitHub Pages"
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/www/dist
          publish_branch: gh-pages
          commit_message: "Deploy to GitHub Pages"
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          tag_name: ${{ steps.prepare_tag.outputs.DEPLOY_TAG_NAME }}
          tag_message: "Deployment ${{ github.ref_name }}"
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
