name: Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy, e.g. v1.2.3"
        required: false
        type: string
  workflow_run:
    workflows: ["Release"]
    branches: [master]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ github.workspace }}/go.mod
          cache-dependency-path: ${{ github.workspace }}/go.sum
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: "Build"
        run: make build

      - name: Prepare tag
        id: prepare_tag
        shell: bash
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_run' && startsWith(github.event.inputs.tag, 'v')
        run: |
          set -e
          TAG_NAME=""
          if [[ "${{ github.event_name }}" == 'workflow_run' ]]; then
            TAG_NAME="${{ github.event.inputs.tag }}"
          else
            TAG_NAME=$(echo "${{ github.ref }}" | sed -e 's/refs\/tags\///')
          fi
          echo "DEPLOY_TAG_NAME=deploy-${TAG_NAME}" >> "${GITHUB_ENV}"

      - name: "Deploy to GitHub Pages"
        if: steps.prepare_tag.outputs.DEPLOY_TAG_NAME != ''
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/www/dist
          publish_branch: gh-pages
          commit_message: "Deploy to GitHub Pages"
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          tag_name: ${{ steps.prepare_tag.outputs.DEPLOY_TAG_NAME }}
          tag_message: "Deployment ${{ github.ref_name }}"
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
