name: Lint

on:
  push:
    branches: [master]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup-go-node
        with:
          skip-node: true

      - name: Install golangci-lint
        run: make install/tools

      - name: Run golangci-lint
        run: make lint/wasm
